-- Expand campaign_analytics table with additional metrics
-- These columns support the generate-daily-report edge function

ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS calls_answered INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS calls_voicemail INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS calls_no_answer INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS avg_duration_seconds INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS demos_booked INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS samples_requested INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS high_interest INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS medium_interest INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS low_interest INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS answer_rate NUMERIC(5,2);
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS conversion_rate NUMERIC(5,2);
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS retries_scheduled INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS retries_completed INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS new_practitioners INTEGER DEFAULT 0;
ALTER TABLE campaign_analytics ADD COLUMN IF NOT EXISTS enriched_practitioners INTEGER DEFAULT 0;

-- Add comment for documentation
COMMENT ON TABLE campaign_analytics IS 'Daily campaign statistics generated by generate-daily-report edge function';
